# Generated by Django 5.1.4 on 2025-01-12 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='selected_flavour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.flavour'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('COD', 'COD')], default='ONLINE', max_length=100),
        ),
    ]
